# Generated by Django 6.0.2 on 2026-05-19 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido1', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_defuncion', models.DateField(blank=True, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=200, null=True)),
                ('lugar_defuncion', models.CharField(blank=True, max_length=200, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_personas/')),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_como_madre', to='arbol_app.persona')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_como_padre', to='arbol_app.persona')),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido1', 'nombre', 'fecha_nacimiento'],
                'indexes': [models.Index(fields=['padre'], name='arbol_app_p_padre_i_367e45_idx'), models.Index(fields=['madre'], name='arbol_app_p_madre_i_53cc8d_idx')],
            },
        ),
    ]
